services:
  # Elasticsearch
  elasticsearch:
    image: elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - kafka-network

  # Kibana (optional for visualization)
  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    networks:
      - kafka-network
    depends_on:
      - elasticsearch

networks:
  kafka-network:
    driver: bridge